-- Private, owner-scoped accountability data. Every application query must still
-- authorize and filter by owner_id; composite foreign keys prevent cross-owner links.

CREATE TABLE accountability_habit_days (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    habit_key TEXT NOT NULL CHECK (habit_key ~ '^[a-z0-9][a-z0-9._:-]{0,79}$'),
    local_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'unknown' CHECK (status IN ('complete', 'incomplete', 'unknown')),
    activity TEXT CHECK (activity IS NULL OR length(activity) <= 200),
    duration_minutes INTEGER CHECK (duration_minutes BETWEEN 0 AND 1440),
    outreach_count INTEGER CHECK (outreach_count BETWEEN 0 AND 999),
    outreach_channel TEXT CHECK (outreach_channel IN ('email', 'linkedin', 'phone', 'in_person', 'other')),
    email_drafted_count INTEGER NOT NULL DEFAULT 0 CHECK (email_drafted_count BETWEEN 0 AND 10000),
    email_sent_count INTEGER NOT NULL DEFAULT 0 CHECK (email_sent_count BETWEEN 0 AND 10000),
    video_stage TEXT CHECK (video_stage IN ('idea', 'planned', 'scripted', 'recorded', 'edited', 'published')),
    notes TEXT CHECK (notes IS NULL OR length(notes) <= 4000),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_habit_days_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_habit_days_owner_key_date_key UNIQUE (owner_id, habit_key, local_date),
    CONSTRAINT accountability_habit_days_outreach_requires_channel_check CHECK (
        outreach_count IS NULL OR outreach_count = 0 OR outreach_channel IS NOT NULL
    )
);

CREATE INDEX accountability_habit_days_owner_date_idx
    ON accountability_habit_days (owner_id, local_date DESC, habit_key);

CREATE TABLE accountability_idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    operation_key TEXT NOT NULL CHECK (operation_key ~ '^[a-z][a-z0-9._:-]{0,95}$'),
    idempotency_key_hash BYTEA NOT NULL CHECK (octet_length(idempotency_key_hash) = 32),
    request_hash BYTEA NOT NULL CHECK (octet_length(request_hash) = 32),
    response_status SMALLINT CHECK (response_status BETWEEN 100 AND 599),
    result_resource_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    CONSTRAINT accountability_idempotency_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_idempotency_expiry_check CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE UNIQUE INDEX accountability_idempotency_owner_operation_key_idx
    ON accountability_idempotency_keys (owner_id, operation_key, idempotency_key_hash);
CREATE INDEX accountability_idempotency_expiry_idx
    ON accountability_idempotency_keys (expires_at)
    WHERE expires_at IS NOT NULL;

CREATE TABLE accountability_habit_events (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    habit_key TEXT NOT NULL,
    local_date DATE NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('status_set', 'status_cleared')),
    status TEXT CHECK (status IN ('complete', 'incomplete', 'unknown')),
    activity TEXT CHECK (activity IS NULL OR length(activity) <= 200),
    duration_minutes INTEGER CHECK (duration_minutes BETWEEN 0 AND 1440),
    outreach_count INTEGER CHECK (outreach_count BETWEEN 0 AND 999),
    outreach_channel TEXT CHECK (outreach_channel IN ('email', 'linkedin', 'phone', 'in_person', 'other')),
    email_drafted_count INTEGER NOT NULL DEFAULT 0 CHECK (email_drafted_count BETWEEN 0 AND 10000),
    email_sent_count INTEGER NOT NULL DEFAULT 0 CHECK (email_sent_count BETWEEN 0 AND 10000),
    video_stage TEXT CHECK (video_stage IN ('idea', 'planned', 'scripted', 'recorded', 'edited', 'published')),
    notes TEXT CHECK (notes IS NULL OR length(notes) <= 4000),
    idempotency_key_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_habit_events_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_habit_events_status_shape_check CHECK (
        (event_type = 'status_set' AND status IS NOT NULL)
        OR (event_type = 'status_cleared' AND status IS NULL)
    ),
    CONSTRAINT accountability_habit_events_outreach_requires_channel_check CHECK (
        outreach_count IS NULL OR outreach_count = 0 OR outreach_channel IS NOT NULL
    ),
    CONSTRAINT accountability_habit_events_owner_day_fk
        FOREIGN KEY (owner_id, habit_key, local_date)
        REFERENCES accountability_habit_days (owner_id, habit_key, local_date)
        ON DELETE CASCADE,
    CONSTRAINT accountability_habit_events_idempotency_fk
        FOREIGN KEY (owner_id, idempotency_key_id)
        REFERENCES accountability_idempotency_keys (owner_id, id)
        ON DELETE CASCADE
);

CREATE INDEX accountability_habit_events_owner_day_idx
    ON accountability_habit_events (owner_id, habit_key, local_date DESC, occurred_at DESC);

CREATE TABLE accountability_no_fap_days (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    local_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('success', 'relapse', 'not_tracked')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_no_fap_days_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_no_fap_days_owner_date_key UNIQUE (owner_id, local_date)
);

CREATE INDEX accountability_no_fap_days_owner_date_idx
    ON accountability_no_fap_days (owner_id, local_date DESC);

CREATE TABLE accountability_reminders (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    slot_id TEXT NOT NULL CHECK (slot_id ~ '^[a-z0-9][a-z0-9._:-]{0,63}$'),
    local_time TIME NOT NULL,
    time_zone TEXT NOT NULL DEFAULT 'Asia/Kolkata' CHECK (time_zone = 'Asia/Kolkata'),
    weekdays SMALLINT[] NOT NULL DEFAULT ARRAY[1, 2, 3, 4, 5, 6, 7]::SMALLINT[],
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_reminders_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_reminders_owner_slot_key UNIQUE (owner_id, slot_id),
    CONSTRAINT accountability_reminders_owner_id_slot_key UNIQUE (owner_id, id, slot_id),
    CONSTRAINT accountability_reminders_weekdays_check CHECK (
        cardinality(weekdays) BETWEEN 1 AND 7
        AND weekdays <@ ARRAY[1, 2, 3, 4, 5, 6, 7]::SMALLINT[]
    )
);

CREATE INDEX accountability_reminders_enabled_owner_idx
    ON accountability_reminders (owner_id, local_time)
    WHERE enabled;

CREATE TABLE accountability_reminder_deliveries (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    reminder_id UUID NOT NULL,
    slot_id TEXT NOT NULL CHECK (slot_id ~ '^[a-z0-9][a-z0-9._:-]{0,63}$'),
    local_date DATE NOT NULL,
    delivery_key_hash BYTEA NOT NULL CHECK (octet_length(delivery_key_hash) = 32),
    provider TEXT NOT NULL CHECK (provider IN ('in_app', 'email', 'push')),
    provider_delivery_id TEXT CHECK (provider_delivery_id IS NULL OR length(provider_delivery_id) <= 255),
    status TEXT NOT NULL CHECK (status IN ('claimed', 'sent', 'failed', 'suppressed')),
    claim_token UUID,
    claim_expires_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    attempted_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    error_code TEXT CHECK (error_code IS NULL OR error_code ~ '^[A-Z0-9_-]{1,64}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_reminder_deliveries_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_reminder_deliveries_owner_ref_key
        UNIQUE (owner_id, id, reminder_id, slot_id, local_date),
    CONSTRAINT accountability_reminder_deliveries_owner_slot_date_key UNIQUE (owner_id, slot_id, local_date),
    CONSTRAINT accountability_reminder_deliveries_owner_key_hash_key UNIQUE (owner_id, delivery_key_hash),
    CONSTRAINT accountability_reminder_deliveries_claim_shape_check CHECK (
        (status = 'claimed' AND claim_token IS NOT NULL AND claim_expires_at IS NOT NULL AND sent_at IS NULL)
        OR (status <> 'claimed' AND claim_token IS NULL AND claim_expires_at IS NULL)
    ),
    CONSTRAINT accountability_reminder_deliveries_sent_shape_check CHECK (
        (status = 'sent' AND provider_delivery_id IS NOT NULL AND sent_at IS NOT NULL
            AND attempted_at IS NOT NULL AND attempt_count > 0)
        OR (status = 'failed' AND sent_at IS NULL AND attempted_at IS NOT NULL AND attempt_count > 0)
        OR (status IN ('claimed', 'suppressed') AND sent_at IS NULL)
    ),
    CONSTRAINT accountability_reminder_deliveries_reminder_fk
        FOREIGN KEY (owner_id, reminder_id, slot_id)
        REFERENCES accountability_reminders (owner_id, id, slot_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX accountability_reminder_deliveries_provider_id_idx
    ON accountability_reminder_deliveries (owner_id, provider, provider_delivery_id)
    WHERE provider_delivery_id IS NOT NULL;
CREATE INDEX accountability_reminder_deliveries_expiring_claim_idx
    ON accountability_reminder_deliveries (claim_expires_at)
    WHERE status = 'claimed';

CREATE TABLE accountability_check_ins (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    local_date DATE NOT NULL,
    slot_id TEXT NOT NULL CHECK (slot_id ~ '^[a-z0-9][a-z0-9._:-]{0,63}$'),
    scheduled_local_time TIME NOT NULL,
    time_zone TEXT NOT NULL DEFAULT 'Asia/Kolkata' CHECK (time_zone = 'Asia/Kolkata'),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'answered', 'missed')),
    response_text TEXT CHECK (response_text IS NULL OR length(response_text) <= 4000),
    answered_at TIMESTAMPTZ,
    missed_at TIMESTAMPTZ,
    reminder_id UUID,
    reminder_delivery_id UUID,
    reminder_status TEXT NOT NULL DEFAULT 'not_scheduled'
        CHECK (reminder_status IN ('not_scheduled', 'scheduled', 'claimed', 'sent', 'failed', 'suppressed')),
    reminder_attempted_at TIMESTAMPTZ,
    reminder_sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_check_ins_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_check_ins_owner_date_slot_key UNIQUE (owner_id, local_date, slot_id),
    CONSTRAINT accountability_check_ins_status_shape_check CHECK (
        (status = 'pending' AND answered_at IS NULL AND missed_at IS NULL AND response_text IS NULL)
        OR (status = 'answered' AND answered_at IS NOT NULL AND missed_at IS NULL)
        OR (status = 'missed' AND answered_at IS NULL AND missed_at IS NOT NULL AND response_text IS NULL)
    ),
    CONSTRAINT accountability_check_ins_reminder_shape_check CHECK (
        (reminder_status = 'not_scheduled' AND reminder_delivery_id IS NULL
            AND reminder_attempted_at IS NULL AND reminder_sent_at IS NULL)
        OR (reminder_status = 'scheduled' AND reminder_id IS NOT NULL AND reminder_delivery_id IS NULL
            AND reminder_sent_at IS NULL)
        OR (reminder_status = 'claimed' AND reminder_id IS NOT NULL AND reminder_delivery_id IS NOT NULL
            AND reminder_sent_at IS NULL)
        OR (reminder_status = 'sent' AND reminder_id IS NOT NULL AND reminder_delivery_id IS NOT NULL
            AND reminder_attempted_at IS NOT NULL AND reminder_sent_at IS NOT NULL)
        OR (reminder_status = 'failed' AND reminder_id IS NOT NULL AND reminder_delivery_id IS NOT NULL
            AND reminder_attempted_at IS NOT NULL AND reminder_sent_at IS NULL)
        OR (reminder_status = 'suppressed' AND reminder_id IS NOT NULL AND reminder_sent_at IS NULL)
    ),
    CONSTRAINT accountability_check_ins_reminder_fk
        FOREIGN KEY (owner_id, reminder_id, slot_id)
        REFERENCES accountability_reminders (owner_id, id, slot_id)
        ON DELETE CASCADE,
    CONSTRAINT accountability_check_ins_delivery_fk
        FOREIGN KEY (owner_id, reminder_delivery_id, reminder_id, slot_id, local_date)
        REFERENCES accountability_reminder_deliveries (owner_id, id, reminder_id, slot_id, local_date)
        ON DELETE CASCADE
);

CREATE INDEX accountability_check_ins_owner_date_idx
    ON accountability_check_ins (owner_id, local_date DESC, scheduled_local_time);

CREATE TABLE accountability_weight_entries (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    local_date DATE NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    original_value NUMERIC(8, 3) NOT NULL CHECK (original_value > 0),
    original_unit TEXT NOT NULL CHECK (original_unit IN ('kg', 'lb', 'st')),
    weight_kg NUMERIC(8, 3) GENERATED ALWAYS AS (
        CASE original_unit
            WHEN 'kg' THEN original_value
            WHEN 'lb' THEN ROUND(original_value * 0.45359237, 3)
            WHEN 'st' THEN ROUND(original_value * 6.35029318, 3)
        END
    ) STORED,
    notes TEXT CHECK (notes IS NULL OR length(notes) <= 2000),
    source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'imported', 'device', 'image')),
    confirmation_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (confirmation_status IN ('pending', 'confirmed', 'rejected')),
    confirmed_at TIMESTAMPTZ,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_weight_entries_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_weight_entries_normalized_range_check CHECK (weight_kg BETWEEN 0.001 AND 1000),
    CONSTRAINT accountability_weight_entries_confirmation_check CHECK (
        (confirmation_status = 'confirmed' AND confirmed_at IS NOT NULL)
        OR (confirmation_status <> 'confirmed' AND confirmed_at IS NULL)
    ),
    CONSTRAINT accountability_weight_entries_primary_confirmed_check CHECK (
        NOT is_primary OR confirmation_status = 'confirmed'
    )
);

CREATE UNIQUE INDEX accountability_weight_entries_primary_day_idx
    ON accountability_weight_entries (owner_id, local_date)
    WHERE is_primary AND confirmation_status = 'confirmed';
CREATE INDEX accountability_weight_entries_owner_date_idx
    ON accountability_weight_entries (owner_id, local_date DESC, measured_at DESC);

CREATE TABLE accountability_media_assets (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    local_date DATE NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('body', 'habit_evidence', 'general')),
    pose TEXT CHECK (pose IN ('front', 'back', 'left_side', 'right_side', 'other')),
    private_notes TEXT CHECK (private_notes IS NULL OR length(private_notes) <= 2000),
    storage_provider TEXT NOT NULL CHECK (storage_provider IN ('r2', 's3')),
    object_key TEXT NOT NULL CHECK (length(object_key) BETWEEN 1 AND 1024),
    display_name TEXT CHECK (display_name IS NULL OR length(display_name) <= 255),
    content_type TEXT NOT NULL CHECK (content_type ~ '^[a-z0-9.+-]+/[a-z0-9.+-]+$'),
    byte_size BIGINT NOT NULL CHECK (byte_size BETWEEN 1 AND 104857600),
    content_sha256 BYTEA CHECK (content_sha256 IS NULL OR octet_length(content_sha256) = 32),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ready', 'failed', 'deleted')),
    uploaded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT accountability_media_assets_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_media_assets_owner_id_hash_key UNIQUE (owner_id, id, content_sha256),
    CONSTRAINT accountability_media_assets_owner_storage_key UNIQUE (owner_id, storage_provider, object_key),
    CONSTRAINT accountability_media_assets_pose_category_check CHECK (pose IS NULL OR category = 'body'),
    CONSTRAINT accountability_media_assets_status_shape_check CHECK (
        (status = 'ready' AND uploaded_at IS NOT NULL AND deleted_at IS NULL)
        OR (status = 'deleted' AND deleted_at IS NOT NULL)
        OR (status IN ('pending', 'failed') AND deleted_at IS NULL)
    )
);

CREATE INDEX accountability_media_assets_owner_date_idx
    ON accountability_media_assets (owner_id, local_date DESC, created_at DESC)
    WHERE status <> 'deleted';

-- A sanitized derivative must be cryptographically bound to its exact private
-- source. Summary approval joins this relation rather than trusting a client
-- supplied source/derivative pair or a storage-key naming convention.
CREATE TABLE accountability_media_derivatives (
    owner_id TEXT NOT NULL,
    source_media_asset_id UUID NOT NULL,
    source_content_sha256 BYTEA NOT NULL CHECK (octet_length(source_content_sha256) = 32),
    derivative_media_asset_id UUID NOT NULL,
    derivative_content_sha256 BYTEA NOT NULL CHECK (octet_length(derivative_content_sha256) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_media_derivatives_pk
        PRIMARY KEY (owner_id, source_media_asset_id, derivative_media_asset_id),
    CONSTRAINT accountability_media_derivatives_distinct_assets_check
        CHECK (source_media_asset_id <> derivative_media_asset_id),
    CONSTRAINT accountability_media_derivatives_one_source_per_derivative_key
        UNIQUE (owner_id, derivative_media_asset_id),
    CONSTRAINT accountability_media_derivatives_one_derivative_per_source_hash_key
        UNIQUE (owner_id, source_media_asset_id, source_content_sha256),
    CONSTRAINT accountability_media_derivatives_exact_pair_key
        UNIQUE (owner_id, source_media_asset_id, source_content_sha256, derivative_media_asset_id, derivative_content_sha256),
    CONSTRAINT accountability_media_derivatives_source_fk
        FOREIGN KEY (owner_id, source_media_asset_id, source_content_sha256)
        REFERENCES accountability_media_assets (owner_id, id, content_sha256)
        ON DELETE CASCADE,
    CONSTRAINT accountability_media_derivatives_derivative_fk
        FOREIGN KEY (owner_id, derivative_media_asset_id, derivative_content_sha256)
        REFERENCES accountability_media_assets (owner_id, id, content_sha256)
        ON DELETE CASCADE
);

CREATE INDEX accountability_media_derivatives_source_idx
    ON accountability_media_derivatives (owner_id, source_media_asset_id, created_at DESC);

CREATE TABLE accountability_habit_day_evidence (
    owner_id TEXT NOT NULL,
    habit_day_id UUID NOT NULL,
    media_asset_id UUID NOT NULL,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_habit_day_evidence_pk PRIMARY KEY (owner_id, habit_day_id, media_asset_id),
    CONSTRAINT accountability_habit_day_evidence_day_fk
        FOREIGN KEY (owner_id, habit_day_id)
        REFERENCES accountability_habit_days (owner_id, id)
        ON DELETE CASCADE,
    CONSTRAINT accountability_habit_day_evidence_media_fk
        FOREIGN KEY (owner_id, media_asset_id)
        REFERENCES accountability_media_assets (owner_id, id)
        ON DELETE CASCADE
);

CREATE TABLE accountability_habit_event_evidence (
    owner_id TEXT NOT NULL,
    habit_event_id UUID NOT NULL,
    media_asset_id UUID NOT NULL,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_habit_event_evidence_pk PRIMARY KEY (owner_id, habit_event_id, media_asset_id),
    CONSTRAINT accountability_habit_event_evidence_event_fk
        FOREIGN KEY (owner_id, habit_event_id)
        REFERENCES accountability_habit_events (owner_id, id)
        ON DELETE CASCADE,
    CONSTRAINT accountability_habit_event_evidence_media_fk
        FOREIGN KEY (owner_id, media_asset_id)
        REFERENCES accountability_media_assets (owner_id, id)
        ON DELETE CASCADE
);

CREATE TABLE accountability_weight_entry_evidence (
    owner_id TEXT NOT NULL,
    weight_entry_id UUID NOT NULL,
    media_asset_id UUID NOT NULL,
    evidence_kind TEXT NOT NULL DEFAULT 'source_image'
        CHECK (evidence_kind IN ('source_image', 'supporting')),
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_weight_entry_evidence_pk
        PRIMARY KEY (owner_id, weight_entry_id, media_asset_id),
    CONSTRAINT accountability_weight_entry_evidence_weight_fk
        FOREIGN KEY (owner_id, weight_entry_id)
        REFERENCES accountability_weight_entries (owner_id, id)
        ON DELETE CASCADE,
    CONSTRAINT accountability_weight_entry_evidence_media_fk
        FOREIGN KEY (owner_id, media_asset_id)
        REFERENCES accountability_media_assets (owner_id, id)
        ON DELETE CASCADE
);

-- Each row is an immutable draft revision. An edit inserts a new id/revision;
-- it must never mutate a revision already approved or published.
CREATE TABLE accountability_summary_draft_groups (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    activity_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_draft_groups_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_summary_draft_groups_owner_date_key UNIQUE (owner_id, activity_date),
    CONSTRAINT accountability_summary_draft_groups_ref_key UNIQUE (owner_id, id, activity_date)
);

CREATE TABLE accountability_summary_drafts (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    draft_id UUID NOT NULL,
    activity_date DATE NOT NULL,
    revision_number INTEGER NOT NULL CHECK (revision_number > 0),
    title TEXT CHECK (title IS NULL OR length(title) <= 200),
    body TEXT NOT NULL CHECK (length(body) <= 50000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_drafts_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_summary_drafts_revision_key UNIQUE (owner_id, draft_id, revision_number),
    CONSTRAINT accountability_summary_drafts_revision_ref_key
        UNIQUE (owner_id, id, draft_id, revision_number, activity_date),
    CONSTRAINT accountability_summary_drafts_group_fk
        FOREIGN KEY (owner_id, draft_id, activity_date)
        REFERENCES accountability_summary_draft_groups (owner_id, id, activity_date)
        ON DELETE CASCADE
);

CREATE INDEX accountability_summary_drafts_owner_activity_date_idx
    ON accountability_summary_drafts (owner_id, activity_date DESC, draft_id, revision_number DESC);

CREATE TABLE accountability_summary_approvals (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    draft_revision_id UUID NOT NULL,
    draft_id UUID NOT NULL,
    draft_revision INTEGER NOT NULL CHECK (draft_revision > 0),
    activity_date DATE NOT NULL,
    approved_by_user_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    title_snapshot TEXT,
    body_snapshot TEXT NOT NULL CHECK (length(body_snapshot) <= 50000),
    content_sha256 BYTEA NOT NULL CHECK (octet_length(content_sha256) = 32),
    approved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_approvals_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_summary_approvals_owner_id_date_key UNIQUE (owner_id, id, activity_date),
    CONSTRAINT accountability_summary_approvals_one_per_revision_key UNIQUE (owner_id, draft_revision_id),
    CONSTRAINT accountability_summary_approvals_owner_approver_check
        CHECK (approved_by_user_id = owner_id),
    CONSTRAINT accountability_summary_approvals_revision_fk
        FOREIGN KEY (owner_id, draft_revision_id, draft_id, draft_revision, activity_date)
        REFERENCES accountability_summary_drafts (owner_id, id, draft_id, revision_number, activity_date)
        ON DELETE CASCADE
);

CREATE INDEX accountability_summary_approvals_owner_approved_idx
    ON accountability_summary_approvals (owner_id, approved_at DESC);

CREATE TABLE accountability_summary_approval_media (
    owner_id TEXT NOT NULL,
    approval_id UUID NOT NULL,
    source_media_asset_id UUID NOT NULL,
    source_content_sha256 BYTEA NOT NULL CHECK (octet_length(source_content_sha256) = 32),
    approved_media_asset_id UUID NOT NULL,
    approved_content_sha256 BYTEA NOT NULL CHECK (octet_length(approved_content_sha256) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_approval_media_pk
        PRIMARY KEY (owner_id, approval_id, source_media_asset_id, approved_media_asset_id),
    CONSTRAINT accountability_summary_approval_media_allowed_asset_key
        UNIQUE (owner_id, approval_id, approved_media_asset_id, approved_content_sha256),
    CONSTRAINT accountability_summary_approval_media_hash_check CHECK (
        source_media_asset_id <> approved_media_asset_id
        OR source_content_sha256 = approved_content_sha256
    ),
    CONSTRAINT accountability_summary_approval_media_approval_fk
        FOREIGN KEY (owner_id, approval_id)
        REFERENCES accountability_summary_approvals (owner_id, id)
        ON DELETE CASCADE,
    CONSTRAINT accountability_summary_approval_media_source_fk
        FOREIGN KEY (owner_id, source_media_asset_id, source_content_sha256)
        REFERENCES accountability_media_assets (owner_id, id, content_sha256)
        ON DELETE CASCADE,
    CONSTRAINT accountability_summary_approval_media_approved_fk
        FOREIGN KEY (owner_id, approved_media_asset_id, approved_content_sha256)
        REFERENCES accountability_media_assets (owner_id, id, content_sha256)
        ON DELETE CASCADE,
    CONSTRAINT accountability_summary_approval_media_derivative_fk
        FOREIGN KEY (
            owner_id, source_media_asset_id, source_content_sha256,
            approved_media_asset_id, approved_content_sha256
        )
        REFERENCES accountability_media_derivatives (
            owner_id, source_media_asset_id, source_content_sha256,
            derivative_media_asset_id, derivative_content_sha256
        )
        ON DELETE CASCADE
);

CREATE TABLE accountability_summary_publications (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    approval_id UUID NOT NULL,
    activity_date DATE NOT NULL,
    idempotency_key_hash BYTEA NOT NULL CHECK (octet_length(idempotency_key_hash) = 32),
    destination TEXT NOT NULL DEFAULT 'random_thoughts' CHECK (destination = 'random_thoughts'),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'published', 'failed', 'canceled')),
    random_thought_id BIGINT REFERENCES random_thoughts (id) ON DELETE RESTRICT,
    provider_reference TEXT CHECK (provider_reference IS NULL OR length(provider_reference) <= 500),
    error_code TEXT CHECK (error_code IS NULL OR error_code ~ '^[A-Z0-9_-]{1,64}$'),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_publications_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_summary_publications_media_ref_key
        UNIQUE (owner_id, id, approval_id, activity_date, random_thought_id),
    CONSTRAINT accountability_summary_publications_snapshot_key UNIQUE (owner_id, approval_id),
    CONSTRAINT accountability_summary_publications_idempotency_key UNIQUE (owner_id, idempotency_key_hash),
    CONSTRAINT accountability_summary_publications_owner_date_destination_key
        UNIQUE (owner_id, activity_date, destination),
    CONSTRAINT accountability_summary_publications_status_shape_check CHECK (
        (status = 'published' AND published_at IS NOT NULL AND random_thought_id IS NOT NULL)
        OR (status <> 'published' AND published_at IS NULL)
    ),
    CONSTRAINT accountability_summary_publications_approval_fk
        FOREIGN KEY (owner_id, approval_id, activity_date)
        REFERENCES accountability_summary_approvals (owner_id, id, activity_date)
        ON DELETE CASCADE
);

CREATE INDEX accountability_summary_publications_owner_requested_idx
    ON accountability_summary_publications (owner_id, requested_at DESC);

ALTER TABLE random_thought_media
    ADD COLUMN IF NOT EXISTS content_sha256 BYTEA;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'random_thought_media_content_sha256_check'
          AND conrelid = 'random_thought_media'::regclass
    ) THEN
        ALTER TABLE random_thought_media
            ADD CONSTRAINT random_thought_media_content_sha256_check
            CHECK (content_sha256 IS NULL OR octet_length(content_sha256) = 32);
    END IF;
END
$migration$;

CREATE UNIQUE INDEX random_thought_media_thought_id_id_hash_idx
    ON random_thought_media (thought_id, id, content_sha256);

CREATE TABLE accountability_summary_publication_events (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL,
    publication_id UUID NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('requested', 'published', 'failed', 'canceled')),
    provider_reference TEXT CHECK (provider_reference IS NULL OR length(provider_reference) <= 500),
    error_code TEXT CHECK (error_code IS NULL OR error_code ~ '^[A-Z0-9_-]{1,64}$'),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_publication_events_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_summary_publication_events_publication_fk
        FOREIGN KEY (owner_id, publication_id)
        REFERENCES accountability_summary_publications (owner_id, id)
        ON DELETE CASCADE
);

CREATE INDEX accountability_summary_publication_events_owner_time_idx
    ON accountability_summary_publication_events (owner_id, publication_id, occurred_at DESC);

CREATE TABLE accountability_summary_publication_media (
    owner_id TEXT NOT NULL,
    publication_id UUID NOT NULL,
    approval_id UUID NOT NULL,
    activity_date DATE NOT NULL,
    approved_media_asset_id UUID NOT NULL,
    approved_content_sha256 BYTEA NOT NULL CHECK (octet_length(approved_content_sha256) = 32),
    random_thought_id BIGINT NOT NULL,
    random_thought_media_id BIGINT NOT NULL,
    published_content_sha256 BYTEA NOT NULL CHECK (octet_length(published_content_sha256) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_summary_publication_media_pk
        PRIMARY KEY (owner_id, publication_id, approved_media_asset_id),
    CONSTRAINT accountability_summary_publication_media_exact_hash_check
        CHECK (published_content_sha256 = approved_content_sha256),
    CONSTRAINT accountability_summary_publication_media_publication_fk
        FOREIGN KEY (owner_id, publication_id, approval_id, activity_date, random_thought_id)
        REFERENCES accountability_summary_publications (owner_id, id, approval_id, activity_date, random_thought_id)
        ON DELETE CASCADE,
    CONSTRAINT accountability_summary_publication_media_approval_asset_fk
        FOREIGN KEY (owner_id, approval_id, approved_media_asset_id, approved_content_sha256)
        REFERENCES accountability_summary_approval_media
            (owner_id, approval_id, approved_media_asset_id, approved_content_sha256)
        ON DELETE CASCADE,
    CONSTRAINT accountability_summary_publication_media_random_thought_fk
        FOREIGN KEY (random_thought_id, random_thought_media_id, published_content_sha256)
        REFERENCES random_thought_media (thought_id, id, content_sha256)
        ON DELETE RESTRICT
);

CREATE TABLE accountability_api_keys (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    key_id TEXT NOT NULL UNIQUE CHECK (key_id ~ '^[A-Za-z0-9_-]{8,40}$'),
    key_prefix TEXT NOT NULL CHECK (length(key_prefix) BETWEEN 4 AND 16),
    label TEXT NOT NULL CHECK (length(label) BETWEEN 1 AND 80),
    verifier_hash BYTEA NOT NULL CHECK (octet_length(verifier_hash) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    CONSTRAINT accountability_api_keys_owner_id_id_key UNIQUE (owner_id, id),
    CONSTRAINT accountability_api_keys_expiry_check CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE INDEX accountability_api_keys_owner_active_idx
    ON accountability_api_keys (owner_id, created_at DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE accountability_api_key_scopes (
    owner_id TEXT NOT NULL,
    api_key_id UUID NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN (
        'content:read',
        'progress:read', 'progress:write',
        'check-ins:read', 'check-ins:write',
        'media:read', 'media:write',
        'summaries:write', 'summaries:publish'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_api_key_scopes_pk PRIMARY KEY (owner_id, api_key_id, scope),
    CONSTRAINT accountability_api_key_scopes_key_fk
        FOREIGN KEY (owner_id, api_key_id)
        REFERENCES accountability_api_keys (owner_id, id)
        ON DELETE CASCADE
);

CREATE TABLE accountability_rate_limit_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    api_key_id UUID,
    bucket_key TEXT NOT NULL CHECK (bucket_key ~ '^[a-z][a-z0-9._:-]{0,95}$'),
    window_start TIMESTAMPTZ NOT NULL,
    window_seconds INTEGER NOT NULL CHECK (window_seconds BETWEEN 1 AND 86400),
    hit_count INTEGER NOT NULL DEFAULT 1 CHECK (hit_count > 0),
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_rate_limit_expiry_check
        CHECK (expires_at = window_start + (window_seconds * INTERVAL '1 second')),
    CONSTRAINT accountability_rate_limit_api_key_owner_fk
        FOREIGN KEY (owner_id, api_key_id)
        REFERENCES accountability_api_keys (owner_id, id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX accountability_rate_limit_owner_window_key
    ON accountability_rate_limit_windows (owner_id, bucket_key, window_start)
    WHERE api_key_id IS NULL;
CREATE UNIQUE INDEX accountability_rate_limit_api_key_window_key
    ON accountability_rate_limit_windows (owner_id, api_key_id, bucket_key, window_start)
    WHERE api_key_id IS NOT NULL;
CREATE INDEX accountability_rate_limit_expiry_idx
    ON accountability_rate_limit_windows (expires_at);

-- Pre-auth MCP requests have no owner/key identity yet. Store only a keyed
-- pseudonymous source digest, never the raw client IP/header value.
CREATE TABLE accountability_pre_auth_rate_limit_windows (
    subject_hash BYTEA NOT NULL CHECK (octet_length(subject_hash) = 32),
    bucket_key TEXT NOT NULL CHECK (bucket_key ~ '^[a-z][a-z0-9._:-]{0,95}$'),
    window_start TIMESTAMPTZ NOT NULL,
    window_seconds INTEGER NOT NULL CHECK (window_seconds BETWEEN 1 AND 86400),
    hit_count INTEGER NOT NULL DEFAULT 1 CHECK (hit_count > 0),
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_pre_auth_rate_limit_window_check
        CHECK (expires_at = window_start + (window_seconds * INTERVAL '1 second')),
    CONSTRAINT accountability_pre_auth_rate_limit_pk
        PRIMARY KEY (subject_hash, bucket_key, window_start)
);

CREATE INDEX accountability_pre_auth_rate_limit_expiry_idx
    ON accountability_pre_auth_rate_limit_windows (expires_at);

CREATE TABLE accountability_audit_events (
    id UUID PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN (
        'api_key.created', 'api_key.revoked', 'summary.approved',
        'summary.published', 'media.deleted', 'reminder.updated', 'weight.corrected'
    )),
    entity_id UUID,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT accountability_audit_events_owner_id_id_key UNIQUE (owner_id, id)
);

CREATE INDEX accountability_audit_events_owner_time_idx
    ON accountability_audit_events (owner_id, occurred_at DESC);

-- Keep source events, draft revisions, approvals and history immutable. User
-- deletion and explicit retention cleanup may still remove rows.
CREATE FUNCTION accountability_reject_history_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'Rows in % are immutable; insert a new revision or history row instead.', TG_TABLE_NAME
        USING ERRCODE = 'integrity_constraint_violation';
    RETURN NEW;
END;
$function$;

CREATE TRIGGER accountability_habit_events_immutable
    BEFORE UPDATE ON accountability_habit_events
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_summary_draft_groups_immutable
    BEFORE UPDATE ON accountability_summary_draft_groups
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_summary_drafts_immutable
    BEFORE UPDATE ON accountability_summary_drafts
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_summary_approvals_immutable
    BEFORE UPDATE ON accountability_summary_approvals
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_summary_approval_media_immutable
    BEFORE UPDATE ON accountability_summary_approval_media
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_media_derivatives_immutable
    BEFORE UPDATE ON accountability_media_derivatives
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_summary_publication_events_immutable
    BEFORE UPDATE ON accountability_summary_publication_events
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_summary_publication_media_immutable
    BEFORE UPDATE ON accountability_summary_publication_media
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
CREATE TRIGGER accountability_audit_events_immutable
    BEFORE UPDATE ON accountability_audit_events
    FOR EACH ROW EXECUTE FUNCTION accountability_reject_history_update();
